name: unstory
description: "A browser-style history abstraction for Dart and Flutter routing."
version: 0.1.0
repository: https://github.com/medz/unrouter

environment:
  sdk: ^3.10.3

dependencies:
  web: ^1.1.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.25.8
